---
title: "Energy generation"
author: "Arkadiusz Jaszczuk"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  word_document: default
---

```{r, echo=FALSE}
knitr::opts_chunk$set(error = TRUE)
```

## Table

```{r,echo=F,results="asis"}

    library(knitr)

options(width = 140)
download.file(url="https://www.pse.pl/getcsv/-/export/csv/PL_GEN_WIATR/data/20221210",
              destfile="20221210.csv",method="curl")
d <- read.table(file="20221210.csv",sep=";",dec=",",header=T,fileEncoding="CP1250")

files = paste("https://www.pse.pl/getcsv/-/export/csv/PL_GEN_WIATR/data/",lapply(gsub("-","",as.character(seq(from=Sys.Date()-6,to=Sys.Date(),by="1 day"))),function(d){d})
                  ,sep ='')
destfiles = paste(lapply(gsub("-","",as.character(seq(from=Sys.Date()-6,to=Sys.Date(),by="1 day"))),function(d){d}),".csv",sep='')

for(i in seq_along(files)){
  download.file(files[i], destfiles[i], mode="wb")
}

dane <- NULL
for (f in files) {
  data <- read.table(f ,sep=";",dec=",",header=T,fileEncoding="CP1250")
  dane <- rbind(dane, data)}


tabela = data.frame("Timestamp" = paste(dane$Data,paste(dane$Godzina, ":00", sep='')), "Wind" = as.numeric(dane$Generacja.źródeł.wiatrowych), "PV" = dane$Generacja.źródeł.fotowoltaicznych)

 kable(tabela, caption="Wind and PV's energy generation in last 7 days")


```

## Plots

```{r, echo=F, results="asis", fig.height=5, fig.width=10}

library('cowplot')
library(ggplot2)

p1 = ggplot(tabela, aes(Timestamp, Wind))+
  geom_bar(
    fill = 'blue',
    data = NULL,
    stat='identity',
    position = "stack")+
  theme(axis.text.x = element_blank(),
        plot.title = element_text(color = "blue", size = 15, 
                                  face = "bold", hjust = 0.5),
        axis.text.y = element_text(face = "bold", 
                                   size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14)
        )+
labs(title = "Wind Generation", color='blue')


p2 = ggplot(tabela, aes(Timestamp, PV))+
  geom_bar(
    fill = 'red',
    data = NULL,
    stat='identity',
    position = "stack")+
  theme(axis.text.x = element_blank(),
        plot.title = element_text(color = "red", size = 15, 
                                  face = "bold", hjust = 0.5),
        axis.text.y = element_text(face = "bold", 
                                   size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14)
  )+
  labs(title = "PV Generation", color='red')

plot_grid(p1, p2)
```